### ISSUE TITLE
tslint rules: allow fast null checks

### ISSUE THREAD

**Issue by micha-f** [contiamo/operational-scripts#21]
**Is your feature request related to a problem? Please describe.**
I'd like to use logical operators to perform fast null checks and perform method or function calls for side effects (e.g. `e && e.preventDefault()`).

Currently this results in tslint complaining about `unused expression, expected an assignment or function call`.

**Describe the solution you'd like**
Modify the tslint rule to be
`"no-unused-expression": [true, "allow-fast-null-checks"]`

**Describe alternatives you've considered**
Not using short circuits for fast null checks. But I quite like them.

**Additional context**
https://palantir.github.io/tslint/rules/no-unused-expression/

**Comment by TejasQ** [comment]
The reasoning behind this lint setting is that expressions really should have a _reason for existing_ outside of being conditionals in order to more clearly describe intent to developers, and to prevent associated pitfalls with performing conditional checks with such expressions. 

Consider the case where _"oh, I'll just use an expression here and it'll be fine"_, yet the expression resolves to a `false` and the use case is a string interpolation. 

```jsx
<MyComponent className={`${thisIsFalseSometimes && "my-class"} my-other-class`}
```

This would unnecessarily give you DOM with `<div class="false my-other-class`, which is unexpected and could lead to unpredictable behavior of an application. This is, in essence, why this rule is necessary.

One possible solution to your use case would be to simply be more explicit about intent:

```js
if (e) {
  e.preventDefault();
}
```

would do the same thing, while being a little more intelligible to future readers.

**Comment by micha-f** [comment]
In the example you made, the expression is actually used as an expression. The example you made does not violate this tslint rule.

**Comment by micha-f** [comment]
I'm ok with leaving the rule as it is. I'm also completely fine with `if (e) e.something()` - which is what I had.
